/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LabJackJNI */

#ifndef _Included_LabJackJNI
#define _Included_LabJackJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LabJackJNI
 * Method:    setPWM
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LabJackJNI_setPWM
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
