#!/bin/sh

export LD_LIBRARY_PATH=/home/jim/workspace/priuspilot/src
export LD_PRELOAD="/usr/lib/i386-linux-gnu/librt.so"
 
LIB=~/pplib

 CP=$LIB/Joystick.jar:$LIB/jna-3.2.4.jar:/home/jim/workspace/priuspilot/bin:$LIB/Jama-1.0.2.jar:$LIB/mbrola.jar:$LIB/freetts-jsapi10.jar:$LIB/jsapi.jar:$LIB/freetts.jar
	

java -Dmbrola.base=/home/jim/mbrola/ -Xincgc -Xnoclassgc -Xbatch -dsa -da -classpath $CP Silly  -frameinterval 0   /dev/video0 -displayratio 1 -debug DEBUG_SERIALNO $@

#java -da -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8888,suspend=n -classpath /home/jim/workspace/WebCamCap/bin/:$CP Silly $@


#java -classpath /home/jim/NetBeansProjects/WebCamCap/build/classes/:$CP Silly  -frameinterval 0 /dev/video0 $@ /dev/video0

