#!/bin/sh
SCRIPT_DIR=$( cd ${0%/*} && pwd -P )
LIB="$SCRIPT_DIR/../pplib"
SRC="$SCRIPT_DIR/../src/"
export LD_LIBRARY_PATH="$LIB"
#export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/librt.so" 

IF=wlx0013ef802622
#sudo ifconfig $IF down
#sudo iwconfig $IF mode monitor
#sudo ifconfig $IF up
#sudo iwconfig $IF channel 6


CP=$SRC/priuspilot.jar:$LIB/Joystick.jar:$LIB/jna-3.2.4.jar:/home/jim/workspace/priuspilot/bin:$LIB/Jama-1.0.2.jar:$LIB/mbrola.jar:$LIB/freetts-jsapi10.jar:$LIB/jsapi.jar:$LIB/freetts.jar
	
make -C $SRC && \
java -Dmbrola.base=/home/jim/mbrola/ -Xnoclassgc -Xbatch -dsa -da -classpath $CP Silly \
    -displaymode 63 -frameinterval 0  \
     /dev/video2 -displayratio 1 \
    $@

#    -trimCheat /host/lanedumps/20231109.091539.log \
#    -trimCheat /host/lanedumps/20231109.091938.log \
#    -trimCheat /host/lanedumps/20231109.092317.log \

#java -da -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8888,suspend=n -classpath /home/jim/workspace/WebCamCap/bin/:$CP Silly $@


#java -classpath /home/jim/NetBeansProjects/WebCamCap/build/classes/:$CP Silly  -frameinterval 0 /dev/video0 $@ /dev/video0

