#!/bin/bash

xrdb $HOME/.Xresources
xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

if [ "$DISPLAY" == ":1" ]; then
	#x-terminal-emulator &
	#sleep .2
	xfce4-terminal --color-bg=white --color-text=black --minimize --hide-scrollbar -e $HOME/src/priuspilot/scripts/microkey.sh &
	sleep 1
	xfce4-terminal --color-bg=white --color-text=black --fullscreen --hide-scrollbar -e $HOME/src/priuspilot/scripts/pploop &
	x-window-manager &
else
	/etc/X11/Xsession
fi

