/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ESPNowJNI */

#ifndef _Included_ESPNowJNI
#define _Included_ESPNowJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ESPNowJNI
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ESPNowJNI_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ESPNowJNI
 * Method:    write
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ESPNowJNI_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ESPNowJNI
 * Method:    read
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ESPNowJNI_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
