/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FrameCaptureJNI */

#ifndef _Included_FrameCaptureJNI
#define _Included_FrameCaptureJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FrameCaptureJNI
 * Method:    configure
 * Signature: (ILjava/lang/String;IIIIIIZLjava/lang/String;IIIIZ)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_configure
  (JNIEnv *, jobject, jint, jstring, jint, jint, jint, jint, jint, jint, jboolean, jstring, jint, jint, jint, jint, jboolean);

/*
 * Class:     FrameCaptureJNI
 * Method:    grabFrame
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_FrameCaptureJNI_grabFrame
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     FrameCaptureJNI
 * Method:    getFrameTimestamp
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_FrameCaptureJNI_getFrameTimestamp
  (JNIEnv *, jobject, jint);

/*
 * Class:     FrameCaptureJNI
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     FrameCaptureJNI
 * Method:    renameCurrentCaptureFile
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_renameCurrentCaptureFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FrameCaptureJNI
 * Method:    discardFrame
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_discardFrame
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FrameCaptureJNI
 * Method:    setCaptureFile
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_setCaptureFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     FrameCaptureJNI
 * Method:    setLogData
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_setLogData
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     FrameCaptureJNI
 * Method:    espnowSend
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FrameCaptureJNI_espnowSend
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
